import React from 'react';
import { Download } from 'lucide-react';
import { jsPDF } from 'jspdf';

/**
 * DownloadChatButton Component (Phase 4.5)
 * Renders a header button that exports the full conversation to PDF using jsPDF.
 * File name format: Groundwater_Report_YYYYMMDD.pdf
 */
export function DownloadChatButton({ messages }) {
  const handleDownload = () => {
    if (!messages || messages.length === 0) return;

    const doc = new jsPDF({ unit: 'mm', format: 'a4' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const marginLeft = 18;
    const marginRight = 18;
    const maxLineWidth = pageWidth - marginLeft - marginRight;
    let y = 20;

    const checkPage = (needed = 12) => {
      if (y + needed > pageHeight - 20) {
        doc.addPage();
        y = 20;
      }
    };

    // Title
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(18);
    doc.setTextColor(0, 120, 140);
    doc.text('Groundwater AI Assistant', marginLeft, y);
    y += 8;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text(`Chat Report — ${new Date().toLocaleDateString('en-IN', {
      year: 'numeric', month: 'long', day: 'numeric',
      hour: '2-digit', minute: '2-digit'
    })}`, marginLeft, y);
    y += 6;

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(marginLeft, y, pageWidth - marginRight, y);
    y += 10;

    // Messages
    messages.forEach((msg) => {
      if (!msg.text && !msg.cardData && !msg.listData) return;

      checkPage(18);

      // Sender label
      const isUser = msg.sender === 'user';
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.setTextColor(isUser ? 0 : 0, isUser ? 100 : 150, isUser ? 180 : 140);
      doc.text(isUser ? 'You' : 'AI Assistant', marginLeft, y);

      // Timestamp
      if (msg.timestamp) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.setTextColor(160, 160, 160);
        doc.text(msg.timestamp, pageWidth - marginRight - 15, y);
      }
      y += 6;

      // Message text
      if (msg.text) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10);
        doc.setTextColor(40, 40, 40);

        // Strip markdown bold markers for clean PDF output
        const cleanText = msg.text.replace(/\*\*/g, '');
        const lines = doc.splitTextToSize(cleanText, maxLineWidth);

        lines.forEach((line) => {
          checkPage(6);
          doc.text(line, marginLeft, y);
          y += 5;
        });
      }

      // Card data
      if (msg.cardData) {
        const card = msg.cardData;
        checkPage(30);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.setTextColor(40, 40, 40);
        doc.text(`${card.district}, ${card.state} (${card.year})`, marginLeft + 4, y);
        y += 5;

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        const cardLines = [
          `Category: ${(card.category || '').replace('_', ' ')}`,
          `Stage of Development: ${card.stageDevelopment}%`,
          `Annual Recharge: ${card.annualRecharge} km³`,
          `Extractable Resources: ${card.extractableResources} km³`,
          `Total Extraction: ${card.totalExtraction} km³`
        ];
        cardLines.forEach((cl) => {
          checkPage(5);
          doc.text(`  • ${cl}`, marginLeft + 4, y);
          y += 5;
        });
      }

      // List data
      if (msg.listData && msg.listData.length > 0) {
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(9);
        doc.setTextColor(40, 40, 40);
        msg.listData.forEach((item) => {
          checkPage(6);
          const line = `  • ${item.title}${item.subtitle ? ' — ' + item.subtitle : ''}: ${item.value}`;
          const wrapped = doc.splitTextToSize(line, maxLineWidth - 4);
          wrapped.forEach((wl) => {
            checkPage(5);
            doc.text(wl, marginLeft + 4, y);
            y += 5;
          });
        });
      }

      y += 6;
    });

    // Footer
    checkPage(15);
    y += 4;
    doc.setDrawColor(200, 200, 200);
    doc.line(marginLeft, y, pageWidth - marginRight, y);
    y += 6;
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Generated by Groundwater AI Assistant — INGRES Database', marginLeft, y);

    // Save
    const now = new Date();
    const dateStr = `${now.getFullYear()}${String(now.getMonth() + 1).padStart(2, '0')}${String(now.getDate()).padStart(2, '0')}`;
    doc.save(`Groundwater_Report_${dateStr}.pdf`);
  };

  const hasMessages = messages && messages.length > 0;

  return (
    <button
      type="button"
      className="download-chat-btn"
      onClick={handleDownload}
      disabled={!hasMessages}
      title="Download chat as PDF"
      aria-label="Download chat as PDF report"
    >
      <Download size={16} />
      <span>Export</span>
    </button>
  );
}

export default DownloadChatButton;
